name: 00. Setup Terraform AWS CH

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./iac/backend
  AWS_REGION: us-east-1
  DYNAMO_LOCK_TABLE: pucrs-crypto-terraform-lock
  S3_STATE: pucrs-crypto-github-action-tfstate-unique

jobs:
  prepare:
    name: 'Criar Recursos de Estado Remoto'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Estado Local)
        id: init
        run: terraform init

      - name: Terraform Apply (Criar S3 e DynamoDB)
        id: apply
        run: terraform apply -auto-approve

      - name: Gerar apply_status.txt
        if: always()
        run: |
          STATUS="success"
          echo "{\"name\": \"setup_aws\", \"apply\": \"${STATUS}\", \"date\": \"$(date '+%Y-%m-%d %H:%M:%S')\"}" > $GITHUB_WORKSPACE/apply_status.txt

      - name: Upload do artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-status
          path: ${{ github.workspace }}/apply_status.txt
          retention-days: 1