name: 009. Destroy Infra AWS

on:
  # ğŸ”¹ ExecuÃ§Ã£o manual via GitHub Actions
  workflow_dispatch:

  ## ğŸ”¹ Opcional: dispara quando o workflow de deploy for concluÃ­do
  #workflow_run:
  #  workflows: ["03. Deploy Infra AWS"]
  #  types:
  #    - completed

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    env:
      TF_VAR_env: ${{ secrets.TF_ENV }}
      AWS_REGION: "us-east-1"

    steps:
      # -----------------------
      # ğŸ”¹ Checkout do repositÃ³rio
      # -----------------------
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

        # -----------------------
      # ğŸ”¹ Setup Terraform
      # -----------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # -----------------------
      # ğŸ”¹ Configurar AWS (OIDC)
      # -----------------------


      - name: ğŸ” Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -----------------------
      # ğŸ”¹ Inicializar Terraform
      # -----------------------
      - name: Terraform Init
        working-directory: ./iac/flow
        run: terraform init -input=false

      # -----------------------
      # ğŸ”¹ Validar Terraform
      # -----------------------
      - name: Terraform Validate
        working-directory: ./iac/flow
        run: terraform validate

      # -----------------------
      # ğŸ”¹ Plano de destruiÃ§Ã£o
      # -----------------------
      - name: Terraform Destroy Plan
        working-directory: ./iac/flow
        run: terraform plan -destroy -out=tfplan.destroy

      # -----------------------
      # ğŸ”¹ Aplicar destruiÃ§Ã£o
      # -----------------------
      - name: Terraform Destroy Apply
        working-directory: ./iac/flow
        run: terraform apply -auto-approve tfplan.destroy
