name: 0. üõ†Ô∏èPrepara√ß√£o Inicial do Terraform Backend (S3/DynamoDB)

on:
  workflow_dispatch:

env:
  TF_WORKING_DIR: ./iac/backend
  AWS_REGION: us-east-1
  # Defina os valores literais aqui, ou use secrets/variaveis se necess√°rio
  DYNAMO_LOCK_TABLE: pucrs-crypto-terraform-lock
  S3_STATE: pucrs-crypto-github-action-tfstate-unique

jobs:
  prepare:
    name: 'Criar Recursos de Estado Remoto'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # Use a mesma vers√£o que est√° no seu setup.yml
          terraform_version: 1.5.0 

      - name: Terraform Init (Estado Local)
        id: init
        # N√£o usa backend-config, usa estado local tempor√°rio
        run: terraform init

      - name: Terraform Apply (Criar S3 e DynamoDB)
        id: apply
        run: terraform apply -auto-approve
