name: 010. Cleanup Artifacts ğŸ§¹

on:
  # ğŸ”¹ Permite execuÃ§Ã£o manual
  workflow_dispatch:

  # ğŸ”¹ Executa automaticamente todo dia Ã s 03:00 UTC
  schedule:
    - cron: "0 3 * * *"

    
concurrency:
  group: terraform
  cancel-in-progress: false
  
jobs:
  # ==========================================================
  # ğŸ§© JOB 1: Verifica se a infraestrutura AWS estÃ¡ OK
  # ==========================================================
  infra-check:
    uses: ./.github/workflows/002_check_infra_aws.yml
    secrets: inherit

  print-infra-output:
    name: Resultado da VerificaÃ§Ã£o de Infraestrutura
    needs: infra-check
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ–¨ Print Infra Output
        run: |
          echo "ğŸ“¢ Infra AWS ainda existe?: ${{ needs.infra-check.outputs.infra_is_ready }}"
          if [ "${{ needs.infra-check.outputs.infra_is_ready }}" == "true" ]; then
            echo "âŒ Infra ainda estÃ¡ criada, abortando!"
            exit 1
          fi

  # ==========================================================
  # ğŸš€ JOB 2:Remove Infra AWS
  # ==========================================================
  cleanup:
    name: ğŸ§¹ Remover Artifacts Antigos
    runs-on: ubuntu-latest
    needs: precheck
    if: needs.precheck.outputs.deploy_allowed == 'true'

    steps:
      - name: ğŸ“¥ Listar artifacts antigos
        id: list
        run: |
          echo "Buscando artifacts com mais de 7 dias..."

          artifacts=$(gh api repos/${{ github.repository }}/actions/artifacts \
            --jq '.artifacts[] | select(.expired == false)' || true)

          if [ -z "$artifacts" ]; then
            echo "Nenhum artifact encontrado."
            echo "ARTIFACT_IDS=" >> $GITHUB_ENV
          else
            echo "$artifacts" | jq -r '.id' > artifact_ids.txt
            echo "ARTIFACT_IDS=$(cat artifact_ids.txt)" >> $GITHUB_ENV
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ§¨ Excluir artifacts
        if: env.ARTIFACT_IDS != ''
        run: |
          echo "Excluindo artifacts antigos..."
          for artifact_id in $ARTIFACT_IDS; do
            echo "ğŸ—‘ï¸ Removendo artifact ID: $artifact_id"
            gh api --method DELETE \
              repos/${{ github.repository }}/actions/artifacts/$artifact_id \
              || true
          done
          echo "âœ¨ Limpeza concluÃ­da!"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ‰ Finalizado
        run: echo "ğŸ‰ Cleanup de artifacts finalizado com sucesso!"
