name: 1. Setup Infra AWS

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Escolha a aÃ§Ã£o do Terraform (plan/apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

env:
  TF_WORKING_DIR: ./iac/flow
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.terraform_action }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    outputs:
      # âœ… Exporta a variÃ¡vel de saÃ­da apply_done
      apply_done: ${{ steps.apply_status.outputs.apply_done }}

    steps:
      - name: ğŸ“¦ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ” Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: âš™ï¸ Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Use a mesma versÃ£o definida em versions.tf

      - name: ğŸ§± Terraform Init
        id: init
        run: terraform init -reconfigure

      - name: ğŸ§© Terraform Plan
        id: plan
        if: always()
        run: terraform plan -out=tfplan


      - name: ğŸš€ Terraform Apply
        id: apply
        if: github.event.inputs.terraform_action == 'apply'
        run: terraform apply -auto-approve tfplan

      
        # âœ… Passo Ãºnico e seguro para criar o arquivo apply_status.txt
      - name: ğŸ§¾ Gerar sinalizador de Apply
        id: apply_status
        if: ${{ always() }}
        run: |
          STATUS="failure"
          if [ "${{ github.event.inputs.terraform_action }}" == "apply" ] && [ "${{ job.status }}" == "success" ]; then
            STATUS="success"
          fi
          echo "{\"name\": \"setup_aws\", \"apply\": \"${STATUS}\", \"date\": \"$(date '+%Y-%m-%d %H:%M:%S')\"}" > apply_status.txt
          cat apply_status.txt


      - name: ğŸ“¤ Upload do artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-status
          path: apply_status.txt