name: 1ï¸âƒ£ Setup Infra AWS

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'AÃ§Ã£o do Terraform (plan/apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

env:
  TF_WORKING_DIR: ./iac/flow
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.terraform_action }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    outputs:
      # âœ… Exporta a variÃ¡vel de saÃ­da apply_done
      apply_done: ${{ steps.apply_status.outputs.apply_done }}

    steps:
      - name: ðŸ“¦ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ” Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: âš™ï¸ Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 # Use a mesma versÃ£o definida em versions.tf

      - name: ðŸ§± Terraform Init
        id: init
        run: terraform init -backend-config=backend.hcl -reconfigure

      - name: ðŸ§© Terraform Plan
        id: plan
        if: github.event.inputs.terraform_action == 'plan'
        run: terraform plan -no-color

      - name: ðŸš€ Terraform Apply
        id: apply
        if: github.event.inputs.terraform_action == 'apply'
        run: terraform apply -auto-approve

      - name: ðŸ’¡ Exibir URL da API Gateway
        run: |
          API_URL=$(terraform output -raw api_gateway_invoke_url)
          echo "ðŸš€ URL da API Gateway: $API_URL"
          echo "API_URL=$API_URL" >> $GITHUB_ENV
          
      - name: ðŸ Marcar Apply ConcluÃ­do
        if: ${{ github.event.inputs.terraform_action == 'apply' }}
        id: apply_status
        run: echo "apply_done=true" >> $GITHUB_OUTPUT
