env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: pucrs-crypto-api-repo
  ECS_CLUSTER: pucrs-crypto-cluster
  ECS_SERVICE: pucrs-crypto-api-service
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: crypto-api-container