name: Setup AWS Environment

env:
  TF_WORKING_DIR: iac
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.4.6

on:
  workflow_dispatch:  # executa manualmente apenas uma vez

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Passo 0: Checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v2

      # Passo 1: Teste básico para conferir se os secrets existem
      - name: Check AWS Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID exists? ${AWS_ACCESS_KEY_ID:+yes}"
          echo "AWS_SECRET_ACCESS_KEY exists? ${AWS_SECRET_ACCESS_KEY:+yes}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Passo 2: Configurar as credenciais da AWS
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Passo 3: Instalar o Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # Passo 4: Verificar formatação do Terraform
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Passo 5: Validar o Terraform
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Passo 6: Inicializar o Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

        # Passo 7: Executar Terraform Plan
       name: Terraform Plan
       run: terraform plan
       working-directory: ${{ env.TF_WORKING_DIR }}

       # Passo 8: Aplicar o Terraform apenas no branch main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}