name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Checkout do repositório
    - name: Check out repository
      uses: actions/checkout@v2

    # Passo 2: Configurar as credenciais da AWS
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Altere para a região desejada

    # Passo 3: Instalar o Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6 # Altere para a versão do Terraform desejada

    # Passo 4: Navegar para o diretório onde está o código Terraform
    - name: Change working directory to IAC
      run: cd IAC

    # Passo 5: Inicializar o Terraform
    - name: Initialize Terraform
      run: terraform init
      working-directory: IAC  # Fazendo isso diretamente no diretório IAC

    # Passo 6: Verificar o plano do Terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: IAC

    # Passo 7: Aplicar o plano do Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: IAC
