name: Terraform CI/CD

env:
  TF_WORKING_DIR: iac
  AWS_REGION: us-east-1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Passo 0: Checkout do repositório
    - name: Check out repository
      uses: actions/checkout@v2


    # Passo 1: Checkout do repositório
    - name: Teste básico para conferir se os secrets existem
      run: |
        echo "AWS_ACCESS_KEY_ID exists? ${AWS_ACCESS_KEY_ID:+yes}"
        echo "AWS_SECRET_ACCESS_KEY exists? ${AWS_SECRET_ACCESS_KEY:+yes}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Passo 2: Configurar as credenciais da AWS
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }} 

    # Passo 3: Instalar o Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    # Passo 4: Inicializar o Terraform
    - name: Initialize Terraform
      run: terraform init
      working-directory: ${{ env.TF_WORKING_DIR }}

    # Passo 5: Verificar o plano do Terraform
    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{ env.TF_WORKING_DIR }}

    # Passo 6: Aplicar o plano do Terraform
    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ env.TF_WORKING_DIR }}
