name: 游대 2. Update API (ECS Fargate)

on:
  push:
    branches:
      - main
    paths:
      - 'api/**' # 仇勇 Trigger: Apenas quando h치 push na pasta da API

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: pucrs-crypto-api-repo # ECR Repo Name
  TF_WORKING_DIR: ./iac

jobs:
  deploy_api:
    name: Build, Push & Deploy ECS Task
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 1. Login no ECR e Defini칞칚o da Tag
      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir Vari치veis de Imagem
        id: vars
        run: |
          # Usa o SHA do commit como tag, limitando aos primeiros 7 caracteres
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          
          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
          echo "ECR_URI=$ECR_URI" >> $GITHUB_OUTPUT

      # 2. Build da Imagem e Push para ECR
      - name: Build, Tag e Push da Imagem
        run: |
          docker build -t ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }} ./api 
          docker push ${{ steps.vars.outputs.ECR_URI }}:${{ steps.vars.outputs.IMAGE_TAG }}

      # 3. Deploy com Terraform
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0 

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply (Deploy)
        run: |
          # 仇勇 Passa o SHA do commit (IMAGE_TAG) para a vari치vel do Terraform
          terraform apply -auto-approve -var="image_tag=${{ steps.vars.outputs.IMAGE_TAG }}"
        working-directory: ${{ env.TF_WORKING_DIR }}